import React, { useEffect, useState } from "react";
import Head from 'next/head'
import axios from "axios";
import EditPost from "../../components/EditPost/EditPost";
import { useRouter } from "next/router";

const id = () => {
  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-[5%] md:px-[20%] bg-slate-100 py-10">
        <EditPost />
      </main>
    </div>
  );
};

export default id;
