import Head from 'next/head'
import Image from 'next/image'
import Posts from '../components/Post/Posts'


export default function Home() {

  return (
    <div>
      <Head>
        <title>Blog-app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-[5%] md:px-[20%] bg-slate-50'>
        {/* ==== All posts */}
        <Posts />
      </main>
    </div>
  )
}
